# configs/det/test.yaml

seed: 1337
device: cuda
out_dir: outputs/det/test

cache:
  torch_home: weights

data:
  root: data/sized_rectangles_unfilled
  limit_per_split: null

model:
  num_classes: 2
  local_backbone_weights: weights/resnet50-0676ba61.pth

train:
  epochs: 2
  batch_size: 4
  num_workers: 4
  lr: 0.005
  weight_decay: 0.0005
  optimizer: sgd
  scheduler:
    name: null                           # No Scheduler For Quick Test
  amp: true
  log_every: 50
  grad_clip: 0.0                          # No Gradient Clipping

eval:
  run_during_train: true
  batch_size: 1
  num_workers: 2

early_stopping:
  monitor: ap50_global
