# configs/det/test_cust.yaml
seed: 42
device: cuda   # or "cpu"

data:
  root: "data/sized_squares_unfilled"
  limit_per_split: 25

model:
  num_classes: 2
  custom: true
  anchor_sizes:
    - [16, 32, 64]
    - [32, 64, 128]
    - [64, 128, 256]
    - [128, 256, 512]
    - [256, 512, 1024]
  anchor_ratios: [0.33, 0.5, 1.0, 2.0, 3.0]   # wider & taller than default
  box_detections_per_img: 100

train:
  epochs: 2
  batch_size: 2
  num_workers: 2
  log_every: 5

eval:
  batch_size: 1
  num_workers: 2
  run_during_train: true

optim:
  lr: 0.001
  momentum: 0.9
  weight_decay: 1e-4

out_dir: outputs/det/test_cust_bal
