
seed: 42
device: cuda

data:
  root: "data/sized_squares_unfilled"
  limit_per_split: 25

model:
  num_classes: 2
  custom: true
  anchor_sizes:
    - [8, 16, 32]       # smaller at lower FPN levels
    - [16, 32, 64]
    - [32, 64, 128]
    - [64, 128, 256]
    - [128, 256, 512]
  anchor_ratios: [0.25, 0.33, 0.5, 1.0, 2.0, 3.0, 4.0]   # very skinny â†’ very wide
  box_detections_per_img: 150
  rpn_pre_nms_top_n_train: 3000
  rpn_pre_nms_top_n_test: 1500
  rpn_post_nms_top_n_train: 3000
  rpn_post_nms_top_n_test: 1500

train:
  epochs: 2
  batch_size: 2
  num_workers: 2
  log_every: 5

eval:
  batch_size: 1
  num_workers: 2
  run_during_train: true

optim:
  lr: 0.001
  momentum: 0.9
  weight_decay: 1e-4

out_dir: outputs/det/test_cust_extr
