# configs/det/test.yaml

seed: 1337
device: cuda
out_dir: outputs/det/test

# Cache Settings
cache:
  torch_home: weights

# Data Settings
data:
  root: data/sized_squares_unfilled
  limit_per_split: null

# Model Settings
model:
  num_classes: 2
  local_backbone_weights: weights/resnet50-0676ba61.pth

# Training Settings
train:
  epochs: 2
  batch_size: 4
  num_workers: 4
  lr: 0.005
  weight_decay: 0.0005
  optimizer: sgd
  scheduler:
    name:
  amp: true
  log_every: 50
  grad_clip: null

# Validation Settings
eval:
  run_during_train: true
  batch_size: 1
  num_workers: 2

# Early Stopping Settings
early_stopping:
  monitor: ap50_global
