# configs/det/test.yaml
seed: 42
device: cuda # or "cpu"

data:
  root: "data/sized_squares_unfilled"
  limit_per_split: 25

model:
  num_classes: 2 # Foreground + background
  custom: false

train:
  epochs: 2
  batch_size: 2
  num_workers: 2
  log_every: 5

eval:
  batch_size: 1
  num_workers: 2
  run_during_train: true

optim:
  lr: 0.001
  momentum: 0.9
  weight_decay: 1e-4

out_dir: outputs/det/test
